---
    - name: 'Download & unarchive wordpress'
      unarchive:
        src: 'https://wordpress.org/latest.tar.gz'
        dest: '/var/www/'
        remote_src: true
      become: true
    - name: 'Copy wp-config for datebase'
      ansible.builtin.copy:
        src: '/home/{{ user.stdout }}/ansible_homework_by_roles/wp-config.php'  
        dest: '/var/www/wordpress/wp-config.php'
        mode: '0664'
      become: true
    - name: 'Set ownership'
      file:
        path: '/var/www/wordpress'
        state: 'directory'
        recurse: true
        owner: 'www-data'
        group: 'www-data'
      become: true
   
...
